# This is a basic workflow to help you get started with Actions
name: Tests

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master
  # branch
  push:
    branches-ignore:
      - 'master'
  pull_request:
    branches-ignore:
      - 'master'

      # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    name: Test app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node Version
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Install latest Chrome
        run: |
          sudo apt update
          sudo apt --only-upgrade install google-chrome-stable
          google-chrome --version

      - name: Install dependencies
        run: npm ci

        #- name: Run unit tests
        #run: npm test-headless

      - name: Run integration tests
        run: npm run e2e-headless
